tf-a-builder.yaml: resubmit a juno LAVA job in case of failure
A Juno LAVA job may fail due to possible infrastructure errors* [1], not
related to user changes. These failures are most of the time
transient, related to a particular board itself [2] and not the LAVA
framework. Failures of these type should not impact gerrit impact
gerrit votes negatively.

Although LAVA resubmits automatically the job in case of
infrastructure problem, the latter job is injected with binaries
expected to work (without user changes), making it useless for jenkins
to reuse it, so there is a need to resubmit it.

* In fact, any other HW device can fail with the same reason but TF-A
only test Juno devices.

[1] https://projects.linaro.org/browse/TFC-76
[2] https://projects.linaro.org/browse/LSS-2128

Signed-off-by: Leonardo Sandoval <leonardo.sandoval@linaro.org>
Change-Id: I2ba8bcab2fcf719ec7373cc4943acce7f53f808d

diff --git a/tf-a-builder.yaml b/tf-a-builder.yaml
--- a/tf-a-builder.yaml
+++ b/tf-a-builder.yaml
@@ -179,8 +179,24 @@
                           build-steps:
                             - inject:
                                 properties-file: ${WORKSPACE}/lava.param
-                            - shell:
-                                !include-raw: tf-a-builder/squad.sh
+                            - shell: |
+                                #!/bin/bash
+
+                                squad='tf-a-job-configs/tf-a-builder/squad.sh'
+                                if ! $squad; then
+                                    # Juno jobs may fail due to LAVA lab infrastructure issues (see
+                                    # https://projects.linaro.org/browse/LSS-2128) so we need to
+                                    # resubmit it if first job failed
+                                    if grep -q 'device_type: juno' artefacts/debug/job.yaml; then
+                                        if ! $squad; then
+                                            echo "LAVA JOB RESULT: 1"
+                                        fi
+                                    else
+                                        echo "LAVA JOB RESULT: 1"
+                                    fi
+                                else
+                                    echo "LAVA JOB RESULT: 0"
+                                fi
         - conditional-publisher:
           - condition-kind: file-exists
             on-evaluation-failure: dont-run
